### ISSUE TITLE
내가 등록한 친구 목록을 조회하는 기능 구현

### ISSUE THREAD

**Issue by soochangoforit** [soochangoforit/BankingServer#17]
## 📌Feature Issue
> 내가 등록한 친구 목록을 조회하는 기능 구현
## 📝To-do
- [ ] 내가 등록한 친구 목록을 조회하는 기능 구현 필요
- [ ] 거래량이 많은 친구 계좌가 상위에 위치하도록 구성
- [ ] 헥사고날 아키텍쳐에 맞게 구성해보자
## ETC
> None
