### ISSUE TITLE
계좌 개설 Service 코드에 대한 단위 테스트 코드 작성

### ISSUE THREAD

**Issue by soochangoforit** [soochangoforit/BankingServer#53]
## 📌Feature Issue
> 계좌 개설 Service 코드에 대한 단위 테스트 코드 작성합니다.
## 📝To-do
- [x] MemberAccount Service 단위 테스트 코드 작성
- [x] AccountNumberGenerator Service 단위 테스트 코드 작성
- [x] AccountOpenTx Service 단위 테스트 코드 작성
- [x] AccountOpen Service 단위 테스트 코드 작성    
## ETC
> None
